In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('melb_data.csv')
features = df.drop(['Price'], axis=1)
labels = df['Price']

In [ ]:
numeric_features = features.select_dtypes(include=[np.number])
categorical_features = features.select_dtypes(exclude=[np.number])
categorical_features = categorical_features.fillna(categorical_features.mode().iloc[0], inplace=True)
numeric_features = numeric_features.fillna(numeric_features.mean(), inplace=True)

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname
0,Abbotsford,85 Turner St,h,S,Biggin,3/12/2016,Yarra,Northern Metropolitan
1,Abbotsford,25 Bloomburg St,h,S,Biggin,4/02/2016,Yarra,Northern Metropolitan
2,Abbotsford,5 Charles St,h,SP,Biggin,4/03/2017,Yarra,Northern Metropolitan
3,Abbotsford,40 Federation La,h,PI,Biggin,4/03/2017,Yarra,Northern Metropolitan
4,Abbotsford,55a Park St,h,VB,Nelson,4/06/2016,Yarra,Northern Metropolitan

In [ ]:
categorical_dummies = pd.get_dummies(categorical_features)
updated_dataset = pd.concat([numeric_features, categorical_dummies], axis=1)
updated_dataset.head()

,Suburb_Abbotsford,Suburb_Aberfeldie,Suburb_Airport West,Suburb_Albanvale,Suburb_Albert Park,Suburb_Albion,Suburb_Alphington,Suburb_Altona,Suburb_Altona Meadows,Suburb_Altona North,...,CouncilArea_Yarra,CouncilArea_Yarra Ranges,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
0,True,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False