In [24]:
import numpy as np
import pandas as pd
import sklearn as sk
import scipy as sp
import pickle

In [6]:
df = pd.read_csv('cars.csv')
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [20]:
features = df.drop(['price', 'car_ID', 'CarName'], axis=1)
labels = df['price']

numeric_features = features.select_dtypes(include=[np.number])
categorical_features = features.select_dtypes(exclude=[np.number])
numeric_features = numeric_features.fillna(numeric_features.mean(), inplace=True)
categorical_features = categorical_features.fillna(categorical_features.mode().iloc[0], inplace=True)

In [21]:
categorical_dummies = pd.get_dummies(categorical_features, drop_first=True, dtype=float)
updated_dataset = pd.concat([numeric_features, categorical_dummies], axis=1)
updated_dataset.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [22]:
X_train, X_test, Y_train, Y_test = sk.model_selection.train_test_split(
    updated_dataset,
    labels,
    test_size=0.2, 
    random_state=42
)

In [25]:
model = sk.linear_model.LinearRegression()
model.fit(X_train, Y_train)
model.score(X_test, Y_test)

0.8925566700320242

In [ ]:
pickle.dump(model, open('cars_model.pkl', 'wb'))